# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from pessoa import Pessoa
from cadastro import Cadastro


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Cadastro = QtWidgets.QLabel(self.centralwidget)
        self.Cadastro.setGeometry(QtCore.QRect(230, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Cadastro.setFont(font)
        self.Cadastro.setObjectName("Cadastro")
        self.InputNm = QtWidgets.QLineEdit(self.centralwidget)
        self.InputNm.setGeometry(QtCore.QRect(160, 90, 311, 20))
        self.InputNm.setObjectName("InputNm")
        self.Nome = QtWidgets.QLabel(self.centralwidget)
        self.Nome.setGeometry(QtCore.QRect(90, 90, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Nome.setFont(font)
        self.Nome.setObjectName("Nome")
        self.CPF_Cd = QtWidgets.QLabel(self.centralwidget)
        self.CPF_Cd.setGeometry(QtCore.QRect(90, 130, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.CPF_Cd.setFont(font)
        self.CPF_Cd.setObjectName("CPF_Cd")
        self.InputCp = QtWidgets.QLineEdit(self.centralwidget)
        self.InputCp.setGeometry(QtCore.QRect(160, 130, 91, 20))
        self.InputCp.setObjectName("InputCp")
        self.Endereco = QtWidgets.QLabel(self.centralwidget)
        self.Endereco.setGeometry(QtCore.QRect(90, 180, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Endereco.setFont(font)
        self.Endereco.setObjectName("Endereco")
        self.InputEn = QtWidgets.QLineEdit(self.centralwidget)
        self.InputEn.setGeometry(QtCore.QRect(160, 180, 311, 20))
        self.InputEn.setObjectName("InputEn")
        self.Nasci = QtWidgets.QLabel(self.centralwidget)
        self.Nasci.setGeometry(QtCore.QRect(90, 230, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Nasci.setFont(font)
        self.Nasci.setObjectName("Nasci")
        self.InputNa = QtWidgets.QLineEdit(self.centralwidget)
        self.InputNa.setGeometry(QtCore.QRect(240, 230, 111, 20))
        self.InputNa.setObjectName("InputNa")
        self.ButCad = QtWidgets.QPushButton(self.centralwidget)
        self.ButCad.setGeometry(QtCore.QRect(340, 270, 131, 23))
        self.ButCad.setObjectName("ButCad")
        self.BUSCA = QtWidgets.QLabel(self.centralwidget)
        self.BUSCA.setGeometry(QtCore.QRect(240, 330, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.BUSCA.setFont(font)
        self.BUSCA.setObjectName("BUSCA")
        self.CPF_Bu = QtWidgets.QLabel(self.centralwidget)
        self.CPF_Bu.setGeometry(QtCore.QRect(100, 370, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.CPF_Bu.setFont(font)
        self.CPF_Bu.setObjectName("CPF_Bu")
        self.InputBus = QtWidgets.QLineEdit(self.centralwidget)
        self.InputBus.setGeometry(QtCore.QRect(150, 370, 91, 20))
        self.InputBus.setObjectName("InputBus")
        self.ButBus = QtWidgets.QPushButton(self.centralwidget)
        self.ButBus.setGeometry(QtCore.QRect(260, 370, 71, 23))
        self.ButBus.setObjectName("ButBus")
        self.ResNasci = QtWidgets.QLabel(self.centralwidget)
        self.ResNasci.setGeometry(QtCore.QRect(100, 550, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ResNasci.setFont(font)
        self.ResNasci.setObjectName("ResNasci")
        self.ResNome = QtWidgets.QLabel(self.centralwidget)
        self.ResNome.setGeometry(QtCore.QRect(100, 410, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ResNome.setFont(font)
        self.ResNome.setObjectName("ResNome")
        self.ResEndereco = QtWidgets.QLabel(self.centralwidget)
        self.ResEndereco.setGeometry(QtCore.QRect(100, 500, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ResEndereco.setFont(font)
        self.ResEndereco.setObjectName("ResEndereco")
        self.OutNm = QtWidgets.QLineEdit(self.centralwidget)
        self.OutNm.setGeometry(QtCore.QRect(170, 410, 311, 20))
        self.OutNm.setObjectName("OutNm")
        self.OutNa = QtWidgets.QLineEdit(self.centralwidget)
        self.OutNa.setGeometry(QtCore.QRect(250, 550, 111, 20))
        self.OutNa.setObjectName("OutNa")
        self.OutEn = QtWidgets.QLineEdit(self.centralwidget)
        self.OutEn.setGeometry(QtCore.QRect(170, 500, 311, 20))
        self.OutEn.setObjectName("OutEn")
        self.OutCp = QtWidgets.QLineEdit(self.centralwidget)
        self.OutCp.setGeometry(QtCore.QRect(170, 450, 91, 20))
        self.OutCp.setObjectName("OutCp")
        self.ResCPF = QtWidgets.QLabel(self.centralwidget)
        self.ResCPF.setGeometry(QtCore.QRect(100, 450, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ResCPF.setFont(font)
        self.ResCPF.setObjectName("ResCPF")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #Modificações
        self.cad = Cadastro()
        self.ButCad.clicked.connect(self.botaoCadast)
        self.ButBus.clicked.connect(self.botaoBusc)
    
    def botaoCadast(self):
        nome = self.InputNm.text()
        cpf = self.InputCp.text()
        endereco = self.InputEn.text()
        nascimento = self.InputNa.text()
        if not(nome == '' or cpf == '' or endereco == '' or nascimento == ''):
            p = Pessoa(nome,endereco,cpf,nascimento)
            if(self.cad.cadastra(p)):
                QMessageBox.information(None,'POOII','Cadastro realizado com sucesso!')
                self.InputNm.setText('')
                self.InputCp.setText('')
                self.InputEn.setText('')
                self.InputNa.setText('')
            else:
                QMessageBox.information(None,'POOII','O CPF informado já se encontra cadastrado!')
        else:
            QMessageBox.information(None,'POOII','Todos os campos devem ser preeecidos!')
    
    def botaoBusc(self):
        cpf = self.InputBus.text()
        pessoa = self.cad.busca(cpf)
        if(pessoa!=None):
            self.OutNm.setText(pessoa.nome)
            self.OutCp.setText(pessoa.cpf)
            self.OutEn.setText(pessoa.endereco)
            self.OutNa.setText(pessoa.data_nascimento)
        else:
            QMessageBox.information(None,'POOII','CPF não cadastrado!')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Cadastro.setText(_translate("MainWindow", "CADASTRO"))
        self.Nome.setText(_translate("MainWindow", "Nome"))
        self.CPF_Cd.setText(_translate("MainWindow", "CPF"))
        self.Endereco.setText(_translate("MainWindow", "Endereço"))
        self.Nasci.setText(_translate("MainWindow", "Data de Nascimento"))
        self.ButCad.setText(_translate("MainWindow", "Cadastrar"))
        self.BUSCA.setText(_translate("MainWindow", "BUSCA"))
        self.CPF_Bu.setText(_translate("MainWindow", "CPF"))
        self.ButBus.setText(_translate("MainWindow", "Buscar"))
        self.ResNasci.setText(_translate("MainWindow", "Data de Nascimento"))
        self.ResNome.setText(_translate("MainWindow", "Nome"))
        self.ResEndereco.setText(_translate("MainWindow", "Endereço"))
        self.ResCPF.setText(_translate("MainWindow", "CPF"))
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


