# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inicio.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_inicio(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CdE = QtWidgets.QLabel(self.centralwidget)
        self.CdE.setGeometry(QtCore.QRect(190, 120, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CdE.setFont(font)
        self.CdE.setObjectName("CdE")
        self.BtBus = QtWidgets.QPushButton(self.centralwidget)
        self.BtBus.setGeometry(QtCore.QRect(60, 210, 111, 41))
        self.BtBus.setObjectName("BtBus")
        self.BtCad = QtWidgets.QPushButton(self.centralwidget)
        self.BtCad.setGeometry(QtCore.QRect(360, 210, 111, 41))
        self.BtCad.setObjectName("BtCad")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CdE.setText(_translate("MainWindow", "CONTROLE DE ESTOQUE"))
        self.BtBus.setText(_translate("MainWindow", "Buscar"))
        self.BtCad.setText(_translate("MainWindow", "Cadastrar"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_inicio()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
