# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadas.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Cadastro = QtWidgets.QLabel(self.centralwidget)
        self.Cadastro.setGeometry(QtCore.QRect(230, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Cadastro.setFont(font)
        self.Cadastro.setObjectName("Cadastro")
        self.InputNm = QtWidgets.QLineEdit(self.centralwidget)
        self.InputNm.setGeometry(QtCore.QRect(160, 90, 311, 20))
        self.InputNm.setObjectName("InputNm")
        self.Nome = QtWidgets.QLabel(self.centralwidget)
        self.Nome.setGeometry(QtCore.QRect(90, 90, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Nome.setFont(font)
        self.Nome.setObjectName("Nome")
        self.CPF_Cd = QtWidgets.QLabel(self.centralwidget)
        self.CPF_Cd.setGeometry(QtCore.QRect(90, 130, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.CPF_Cd.setFont(font)
        self.CPF_Cd.setObjectName("CPF_Cd")
        self.InputCp = QtWidgets.QLineEdit(self.centralwidget)
        self.InputCp.setGeometry(QtCore.QRect(160, 130, 91, 20))
        self.InputCp.setObjectName("InputCp")
        self.Endereco = QtWidgets.QLabel(self.centralwidget)
        self.Endereco.setGeometry(QtCore.QRect(90, 180, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Endereco.setFont(font)
        self.Endereco.setObjectName("Endereco")
        self.InputEn = QtWidgets.QLineEdit(self.centralwidget)
        self.InputEn.setGeometry(QtCore.QRect(160, 180, 311, 20))
        self.InputEn.setObjectName("InputEn")
        self.Nasci = QtWidgets.QLabel(self.centralwidget)
        self.Nasci.setGeometry(QtCore.QRect(90, 230, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Nasci.setFont(font)
        self.Nasci.setObjectName("Nasci")
        self.InputNa = QtWidgets.QLineEdit(self.centralwidget)
        self.InputNa.setGeometry(QtCore.QRect(240, 230, 111, 20))
        self.InputNa.setObjectName("InputNa")
        self.ButCad = QtWidgets.QPushButton(self.centralwidget)
        self.ButCad.setGeometry(QtCore.QRect(340, 270, 131, 23))
        self.ButCad.setObjectName("ButCad")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Cadastro.setText(_translate("MainWindow", "CADASTRO"))
        self.Nome.setText(_translate("MainWindow", "Nome"))
        self.CPF_Cd.setText(_translate("MainWindow", "CPF"))
        self.Endereco.setText(_translate("MainWindow", "Endereço"))
        self.Nasci.setText(_translate("MainWindow", "Data de Nascimento"))
        self.ButCad.setText(_translate("MainWindow", "Cadastrar"))
